# Generated by Django 3.1.7 on 2021-03-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.customer', to_field='username')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.serviceprovider', to_field='username')),
            ],
            options={
                'db_table': 'OrderService',
            },
        ),
    ]
