# Generated by Django 3.1.5 on 2021-02-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
